/**
 * Type exports for UCM Editor.
 */

// Error types
export {
  ErrorCode,
  type ErrorCategory,
  type ErrorSeverity,
  type BlockErrorData,
  type SelectionErrorData,
  type EditErrorData,
  type DragErrorData,
  type HistoryErrorData,
  type DiffErrorData,
  type GraphErrorData,
  type DocumentErrorData,
  type InternalErrorData,
  type EditorErrorData,
  type EditorErrorOptions,
  EditorError,
  Errors,
  type Result,
  ok,
  err,
  unwrap,
  unwrapOr,
  map,
  andThen,
} from './errors.js'

// Editor types
export {
  type EditorView,
  type EditorMode,
  type BlockEditState,
  type TextSelection,
  type BlockSelection,
  type SelectionState,
  type DragState,
  type DragPreview,
  type DropZone,
  type BlockRendererProps,
  type ContentEditorProps,
  type GraphLayout,
  type GraphNode,
  type GraphEdge,
  type GraphViewState,
  type DiffChangeType,
  type BlockDiff,
  type TextDiff,
  type MetadataChange,
  type StructuralChange,
  type DocumentDiff,
  type DiffViewState,
  type HistoryEntry,
  type HistoryOperation,
  type HistoryState,
  type BlockMetadataDisplay,
  type EditorConfig,
  DEFAULT_EDITOR_CONFIG,
  type EditorStoreState,
  type EditorStoreActions,
  type EditorStore,
} from './editor.js'

// Event types
export {
  type EditorEventType,
  type DocumentEventData,
  type BlockEventData,
  type SelectionEventData,
  type EditEventData,
  type DragEventData,
  type HistoryEventData,
  type EdgeEventData,
  type ViewEventData,
  type GraphEventData,
  type DiffEventData,
  type ErrorEventData,
  type EditorEventData,
  type EditorEvent,
  type EditorEventHandler,
  type EditorEventEmitter,
  SimpleEventEmitter,
} from './events.js'
